### ISSUE TITLE
Browse DB Tests : 9 FD Plots view > Title missing when "No data to display" on subplots

### ISSUE THREAD

**Issue by charlottegiseleweil** [eesd-epfl/eesd-dashboard#1]
![Screenshot 2021-11-24 at 08 58 18](https://user-images.githubusercontent.com/18381609/143197682-aa626264-1d5f-43b3-b990-a1764b551630.png)

**Comment by PaddyLoeliger** [comment]
Solved.

Now appears with "Title name" - No data to display.

Note, The Name of the unit test has all special characters removed ("#","-",".").
